### ISSUE TITLE
    label_ind = torch.randperm(500).numpy() Why is it used?

### ISSUE THREAD

**Issue by HashmatShadab** [qizhangli/nobox-attacks#2]
I couldn't understand why we use a random permutation of the first 500 classes rather than just using label_ind = [i for i in range(500)] to generate the selected_data.csv. I didn't find any use-case for doing this randomly.  Please explain if there was any reason for doing so

**Comment by qizhangli** [comment]
Dear HashmatShadab, 
Yes, you can also use ```label_ind = [i for i in range(500)]```.
